[progress_bar]
spinner_chars = [
  "â–‰â–Šâ–‹â–Œâ–â–â–â–â–â–Œâ–‹â–Šâ–‰",
  "â â ‚â „â¡€â¢€â  â â ˆ ",
  "â ‹â ™â ¹â ¸â ¼â ´â ¦â §â ‡â  ",
  "â£¾â£½â£»â¢¿â¡¿â£Ÿâ£¯â£· ",
  "â—â—“â—‘â—’",
  "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆâ–‡â–†â–…â–„â–ƒâ–‚",
  "ğŸŒ‘ğŸŒ’ğŸŒ“ğŸŒ”ğŸŒ•ğŸŒ–ğŸŒ—ğŸŒ˜",
  "ğŸ•›ğŸ•ğŸ•‘ğŸ•’ğŸ•“ğŸ•”ğŸ••ğŸ•–ğŸ•—ğŸ•˜ğŸ•™ğŸ•š",
  "â––â–˜â–â–—",
  "â”¤â”˜â”´â””â”œâ”Œâ”¬â”",
  "â—¢â—£â—¤â—¥",
  ".oOÂ°Oo.",
  "-\\|/",
  "â†â†–â†‘â†—â†’â†˜â†“â†™",
  "â–¯â–®â–¯â–®",
  "â „â †â ‡â ‹â ™â ¸â °â  â °â ¸â ™â ‹â ‡â †",
  "â˜€ï¸ğŸŒ¤ï¸â›…ğŸŒ¥ï¸â˜ï¸ğŸŒ¦ï¸ğŸŒ§ï¸â›ˆï¸"
]
progress_bar_chars = [
  "â–ˆâ–“â–’â–‘ ",
  "â–ˆâ–‰â–Šâ–‹â–Œâ–â–â– ",
  "ğŸ¬€ğŸ¬ğŸ¬‚ğŸ¬ƒğŸ¬„ğŸ¬…ğŸ¬†ğŸ¬‡ğŸ¬ˆğŸ¬‰ğŸ¬ŠğŸ¬‹ğŸ¬ŒğŸ¬ğŸ¬ğŸ¬â–",
  "â–ˆğŸ®‡ğŸ®ˆğŸ®‰â–Œ ",
  "â”â•º",
  "â•â•Œ",
  "â”€â•´",
  "âšªâš«",
  "â–°â–±",
  "ğŸ­¶ğŸ­·ğŸ­¸ğŸ­¹ğŸ­ºğŸ­»",
]
spinner_templates = [
  "{spinner:.blue} {msg} | {elapsed} | {bytes}/{total_bytes}",
  "{spinner:.green} {msg:15} {bytes_per_sec:12} | â³ {eta}",
  "{spinner:.yellow} {msg} | {elapsed_precise}",
  "{spinner:.cyan} {human_pos:>7}/{human_len:<7} | {binary_bytes_per_sec}/s",
  "{spinner:.red} [{elapsed}] {prefix:10} {bytes:9} ({per_sec} it/s)",
  "{spinner:.magenta} {msg} | ğŸš€",

]
progress_bar_templates = [
  "[{elapsed_precise}] {msg:10} {bar:40.cyan/blue} {bytes}/{total_bytes} ({eta})",
  "â³ {msg:10} {spinner:.green} [{elapsed_precise}] {bar:40.cyan/blue} {bytes}/{total_bytes}",
  "ğŸ› ï¸ {msg:20} â”‚{bar:40.red/yellow}â”‚ {bytes}/{total_bytes} ({eta})",
  "ğŸ“¦ {msg:20} {bar:40.green/yellow} {bytes}/{total_bytes} â³{eta}",
  "âœ¨ {msg:20} â–•{bar:40.magenta/cyan}â– {bytes}/{total_bytes} ({eta})",
  "{spinner:.green} {msg:20} {bar:40} {bytes}/{total_bytes} ({eta})",
  "ğŸš€ {msg:20} â”ƒ{bar:40.blue/green}â”ƒ {bytes}/{total_bytes} â±ï¸{elapsed}",
  "â±ï¸ {elapsed_precise} {msg:10} {bar:40} {bytes}/{total_bytes}",
  "{msg:20} {bar:40} {bytes}/{total_bytes}",
  "ğŸŒˆ {msg:20} â•‘{bar:40.cyan/purple}â•‘ {bytes}/{total_bytes} ğŸ•‘{eta}",
  "ğŸš€ {msg:20!} {bar:28.cyan/blue} {bytes:>9} / {total_bytes:9} | {binary_bytes_per_sec:12} | â±ï¸ {eta_precise:8}",
  "{spinner:.green} {msg:17} {bar:30.red/yellow} {percent_precise:5}% | {bytes:9} | {eta:4}",
  "ğŸ“¦ {msg:20} {wide_bar:20} {human_pos:>7}/{human_len:<7} ({eta})",
  "â¬‡ï¸ {bytes:9} @ {binary_bytes_per_sec:9}/s | ETA: {eta_precise:8} | {bar:20.magenta/cyan}",
  "ğŸ•¹ï¸ {msg:20} â–{bar:20.green/black}â–Œ {percent:3}% | {elapsed:4} > {eta:4}",
  "ğŸ§® {bar:40} {bytes}/{total_bytes} | {per_sec:6} it/s | â³ {duration_precise}"
]
request_spinner_templates = [
  "{spinner} {msg}",
  "{spinner} {msg:.red}",
  "{spinner} {msg:.blue}",
  "{spinner} {msg:.green}",
  "{spinner} {msg:.gray}",
  "{spinner} {msg:.yellow}",
  "{spinner} {msg:.magenta}",
  "{spinner} {msg:.cyan}",
  "{spinner} {msg:.white}"
]

[download]
parallel_requests = 16
